### ISSUE TITLE
usbip - windows - is this the client only?

### ISSUE THREAD

**Issue by psyciknz** [Oxalin/usbip_windows#8]
I thin I'm using the old v0.2 version, and have installed the driver.

But am I correct that this is the client side only?  and that windows cannot host the device?  I have a windows that I would like to host the usb device for a linux machine.

**Comment by Oxalin** [comment]
Hi to both of you. Sorry for the delay, I'm working on this project on my sparetime, which I don't have a lot right now (spring, baby, tax reports). Now, that being said, you are right, the available driver is a virtual host controller interface (VHCI) only for now, which means it can only deal with remotely shared USB devices and to use them locally as if they were physically connected to the Windows station.

I would like to have a driver (a different one, like what is done under Linux) that would allow to share a USB device from a Windows station, but I'm not there yet. I'm working on stabilizing the current driver and updating libusbip and usbip to be as close as what is available under Linux. When this will be done, I'll work on this new driver, unless someone shifts me at it before.

If you don't mind, I'll close the currect issue, then I'll open a bug and tag it as a feature request so it is clear to anyone that it is planned in some future release.
